### ISSUE TITLE
 custom resolution and refresh rate

### ISSUE THREAD

**Issue by QQ2017** [fufesou/RustDeskIddDriver#1]
How to create a virtual monitor with custom resolution and refresh rate?

**Comment by fufesou** [comment]
As I know, IDD Driver is bonded to the hardware.
You can only hard write params [here](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddDriver/Driver.cpp#L46) .

If you want to create with custom resolution and refresh rate. You can only update modes after created.
1. Change [plugin param](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddDriver/Public.h#L32), and place [modes](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddDriver/Public.h#L42). Then update modes [here](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddDriver/Driver.cpp#L854).
2. Just call [MonitorModesUpdate](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddApp/IddController.h#L122) after monitor is successfully plugged.

**Comment by QQ2017** [comment]
> 

Thank you very much, I will try it

**Comment by QQ2017** [comment]
RustDeskIddDriver.dll  rustdeskidddriver.cat 这两个文件必须打sha256或微软硬件认证签名吗，打了sha1过期签名，在win10 20H1内核上无法安装上驱动.

**Comment by fufesou** [comment]
我没搞过签名这块，在我电脑上测试就直接禁掉签名验证的。

**Comment by QQ2017** [comment]
通过 i 参数安装的驱动，会安装失败，通过手动添加过时设备的方法浏览inf文件，添加成功。

**Comment by fufesou** [comment]
用的管理员权限运行程序吧？
安装失败，在设备管理器那里有新增的未知设备吗？可以点过去，看看有什么错。

**Comment by fufesou** [comment]
> 通过 i 参数安装的驱动，会安装失败，通过手动添加过时设备的方法浏览inf文件，添加成功。

我刚才试了下， 如果没有权限 i 会打印报错，如果安装成功，会提示成功。然后再 c ，就可以再设备管理器看到新增的 driver了。

**Comment by QQ2017** [comment]
> > 通过 i 参数安装的驱动，会安装失败，通过手动添加过时设备的方法浏览inf文件，添加成功。
> 
> 我刚才试了下， 如果没有权限 i 会打印报错，如果安装成功，会提示成功。然后再 c ，就可以再设备管理器看到新增的 driver了。

WIN10 是什么版本呢

**Comment by QQ2017** [comment]
测的时候是管理员权限打开cmd中执行的

**Comment by fufesou** [comment]
> 

win10 19042.1586
但应该跟windows版本无关吧，你既然能在命令行安装。

**Comment by QQ2017** [comment]
![image](https://user-images.githubusercontent.com/23667705/161198677-defeb901-b800-4c7e-a1d8-879b68f9b04d.png)

**Comment by QQ2017** [comment]
结果测试，先按c创建设备，然后在按i就能安装驱动了
![image](https://user-images.githubusercontent.com/23667705/161199303-6490936a-4c16-4254-8b95-5f8072280d7a.png)

**Comment by fufesou** [comment]
> 经过测试，先按c创建设备，然后在按i就能安装驱动了，每次测试都是纯净的系统环境 ![image](https://user-images.githubusercontent.com/23667705/161199303-6490936a-4c16-4254-8b95-5f8072280d7a.png)

厉害，是这样的！我刚看了 [UpdateDriverForPlugAndPlayDevicesA ](https://docs.microsoft.com/en-us/windows/win32/api/newdev/nf-newdev-updatedriverforplugandplaydevicesa) 这个接口。第二个参数是需要指定已经存在设备的硬件id。硬件id或者兼容id是[这里](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddApp/IddController.c#L226)指定的。
应该是先 c 后 i ，不过有些奇怪的是，我这边先 i 后 c 也是没问题的

**Comment by fufesou** [comment]
> 

我这边先i后c没问题，是因为我先前已经创建过 device 了。
那个 destroy device 似乎影响plug monitor。 create device后，然后destory device，也不会影响 i 的执行。
