### ISSUE TITLE
IddCxAdapterInitAsync report the status_not_support error(0xc00000bb)

### ISSUE THREAD

**Issue by frostyWhiteStar** [fufesou/RustDeskIddDriver#2]
Does anybody know why this driver has this "status_not_support" error at IddCxAdapterInitAsync .

**Comment by UMU618** [comment]
https://mp.weixin.qq.com/s?__biz=MjM5MTAwODMyMA==&mid=2649152744&idx=1&sn=f1b4bb1705a84219ca617f6e69ddabfb&chksm=beae6fc789d9e6d12d526f80276363220df76d0a53142b53f66e31b9675109c9aea60c7feb08#rd

**Comment by fufesou** [comment]
@frostyWhiteStar If this issue persists, I'll reopen it.
