### ISSUE TITLE
When following the README.md and attempting to install the driver it fails with last error 0xe000020b

### ISSUE THREAD

**Issue by tiltspinner** [fufesou/RustDeskIddDriver#4]
when running RustDeskIddApp.exe and attemping to install with "i" it fails.

RustDeskIdd: UpdateDriverForPlugAndPlayDevices failed, last error 0xe000020b

I was able to install the driver by first creating device with "c" followed by "i".

The README.md located in the RustDeskIddDriver_x64.zip does not state to create the device first before installilng.

## Steps

1. Double click "RustDeskIddDriver.cer" to install cert.
2. Run "RustDeskIddApp.exe" as administrator.
    **Press "c" to create device. If you get 0xe0000247 error code. You should follow step 3.**  # should be added
    Press "i" to install. If you get 0xe0000247 error code. You should follow step 3.
3. Disable Driver Signature Verification.

This was on a Windows 11 Home version 22H2

**Comment by fufesou** [comment]
Thanks for you feedback.
Yes, you're right.

I'll update the README.md.

The second param of the function [UpdateDriverForPlugAndPlayDevicesA ](https://docs.microsoft.com/en-us/windows/win32/api/newdev/nf-newdev-updatedriverforplugandplaydevicesa) is the [HardwareId](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/hardware-ids) that must exist. The hardware ID or compatible id is set [here](https://github.com/fufesou/RustDeskIddDriver/blob/fc152f4282cc167b0bb32aa12c97c90788f32c3d/RustDeskIddApp/IddController.c#L226).

**Comment by fufesou** [comment]
Close as the `README.md` is updated.
https://github.com/fufesou/RustDeskIddDriver/releases/tag/v0.2.
