### ISSUE TITLE
Can we expand this to add more than 3 monitors ?

### ISSUE THREAD

**Issue by psychrabi** [fufesou/RustDeskIddDriver#5]
I wanted to try and see how many virtual monitors can be added to a system to test an application i have which requires large number of monitors.
I cannot test with physical monitors so virtual monitors is next best thing for me.
I already test with 3 monitors using this driver and app. it worked great.

**Comment by fufesou** [comment]
The num of monitors is not limited.

This file is just a demo app.
https://github.com/fufesou/RustDeskIddDriver/blob/main/RustDeskIddApp/main.c


You can refer this function to add monitors.
https://github.com/fufesou/RustDeskIddDriver/blob/f6d8911a78457d382e1c73c5b6e8b09b9288c400/RustDeskIddApp/IddController.c#L285

You can also modify the code here to change the behavior
https://github.com/fufesou/RustDeskIddDriver/blob/f6d8911a78457d382e1c73c5b6e8b09b9288c400/RustDeskIddApp/main.c#L112

**Comment by psychrabi** [comment]
I tried to update the main.c by adding additional indexes 4, 5, 6 and changing the plugin index to 7, 8,9 for a test, but after compile the app, pressing 4,5,6 is not adding the monitors.

may be i am doing something wrong?
Perhaps you can extend this repo to support any number of monitors?

I would be awesome and great help to me to test my application further

**Comment by fufesou** [comment]
Thanks for your feedback, and sorry for the incorrect reply.

The max monitor count is limited here
https://github.com/fufesou/RustDeskIddDriver/blob/ef8c89b1cc193ad54aa64e9de442c1242f96fe56/RustDeskIddDriver/Driver.h#L120

I've already updated the code. You can use up to 10 monitors in [this branch](https://github.com/fufesou/RustDeskIddDriver/tree/feat/add_monitors_).

You can also set your own max monitor count here.
https://github.com/fufesou/RustDeskIddDriver/blob/fd2f9680574e9ddcbf415429a3a957ae1140c792/RustDeskIddDriver/Driver.h#L122

**Comment by psychrabi** [comment]
Amazing.
Thank you. I can test my application now.
