### ISSUE TITLE
Monitors not persisting after a restart

### ISSUE THREAD

**Issue by psychrabi** [fufesou/RustDeskIddDriver#6]
It worked great to add up to 10 monitors. However, the monitors plugin doesnot persists after reboot.

**Comment by fufesou** [comment]
It seems that a driver management program is needed. And the management program should be registered as a service.

I'm not familiar with the driver management service.
I'll spend a few days working on it.

BTW, this should not be part of this project. I'll add a new reporitory.

Here is an [example](https://github.com/Microsoft/Windows-driver-samples/tree/main/general/DCHU/osrfx2_DCHU_base/osrfx2_DCHU_usersvc).

**Comment by fufesou** [comment]
Alternatively, you could manage the drive all by your own program.

**Comment by fufesou** [comment]
> It seems that a driver management program is needed.

I've studied on the windows service.

It's just a program managed by the system. This program starts running when the system starts up. This program installs drivers and plugs in monitors.

It's not very different from our example program or your own program.
Except for filling the [`SERVICE_TABLE_ENTRY`](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_table_entrya) if you want to create an alone driver management service. [Refer](https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/OneCodeTeam/A%20basic%20Windows%20service%20in%20C%2B%2B%20(CppWindowsService))


A program can be registered as a service by [sc.exe](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create).
Or you could refer to [this example](https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/OneCodeTeam/A%20basic%20Windows%20service%20in%20C%2B%2B%20(CppWindowsService)) if you want to create an alone user service.

I will not add a new repo about the service unless there's more I must do.

**Comment by fufesou** [comment]
Maybe this tag also meet your requirement.

https://github.com/fufesou/RustDeskIddDriver/releases/tag/v0.4
