### ISSUE TITLE
虚拟机上调用 DeviceIoControl 返回错误码0x57(87:参数错误)

### ISSUE THREAD

**Issue by Pansvfj** [fufesou/RustDeskIddDriver#8]
![image](https://github.com/fufesou/RustDeskIddDriver/assets/42718287/69d21027-3d40-4534-aaed-c36aaa54ec73)

**Comment by Pansvfj** [comment]
请问如何解决？

**Comment by fufesou** [comment]
I'm not very familiar with this issue.

1. Make sure Windows version >=1803.
2. Virtual machines may be affected.

<img width="420" alt="1696931243325" src="https://github.com/fufesou/RustDeskIddDriver/assets/13586388/57badfc6-e1ec-4910-8240-7fa0211c1a45">

**Comment by Pansvfj** [comment]
感谢你的回答。我网上看到有人说是在虚拟机上挂载总线驱动上面即可，这是什么意思呢？

**Comment by fufesou** [comment]
抱歉，这个我也不知道 😢

**Comment by Fruneng** [comment]
![无标题](https://github.com/fufesou/RustDeskIddDriver/assets/3040235/4ebddab3-d738-4c95-817d-d7ae183efecb)
@Pansvfj 我似乎也碰到这个问题 你有方法了吗

**Comment by Pansvfj** [comment]
牛逼，我搜索一天都没搞定，我待会把虚拟机的系统升级一下试试

**Comment by Pansvfj** [comment]
> ![无标题](https://user-images.githubusercontent.com/3040235/274123169-825bfc67-1895-4951-a623-b3b0b3e89263.png) @Pansvfj 我似乎也碰到这个问题 在一台物理机上 调试idd 驱动发现初始化失败了 你有方法了吗
> 
> 另外这里也提到这个问题 [microsoft/Windows-driver-samples#654](https://github.com/microsoft/Windows-driver-samples/issues/654) **update**：上面文章里面提了 windows 10 2004 之前的版本的API会有限制IDD驱动 我用的电脑的确是windows 10 1909 ![image](https://user-images.githubusercontent.com/3040235/274152530-388787a8-9261-4a10-a122-b782a9aeacb8.png)
> 
> **update**: 我将windows10 升级至 22H2后 驱动正常加载了 ![image](https://user-images.githubusercontent.com/3040235/274196440-a5b55331-5f19-4769-834a-1c96e461406b.png)

非常感谢你
