### ISSUE TITLE
How do I create a virtual screen with a custom resolution？

### ISSUE THREAD

**Issue by Pansvfj** [fufesou/RustDeskIddDriver#9]
请问如何创建一个自定义分辨率的虚拟屏幕？

**Comment by fufesou** [comment]
[The monitor modes are defined here.

https://github.com/fufesou/RustDeskIddDriver/blob/9371e10a337676cc819c5f427a3a1ed63ba2e842/RustDeskIddDriver/Driver.cpp#L46
](https://github.com/fufesou/RustDeskIddDriver/issues/1#issuecomment-1081393808)

**Comment by Pansvfj** [comment]
好像不太行……

**Comment by Pansvfj** [comment]
好像不太行，请问有例子可以看看吗？
